### ISSUE TITLE
Move RBF pin header from N1 to N2 board

### ISSUE THREAD

**Issue by YanAzer** [spacelab-ufsc/interface-board#26]
Currently the N1 board (1_Interface_Charge_RBF to be mounted in the -Y plane) has a 2 pin header for RBF switch, for the correct integration in the P-POD it must be moved to the N2 board (2_Interface_JTAG to be mounted in the -X plane).

Source: https://static1.squarespace.com/static/5418c831e4b0fa4ecac1bacd/t/56e9b62337013b6c063a655a/1458157095454/cds_rev13_final2.pdf
![image](https://user-images.githubusercontent.com/40373964/85356717-02c27e80-b4e6-11ea-9447-47839a3ddda0.png)
![image](https://user-images.githubusercontent.com/40373964/85357015-d1967e00-b4e6-11ea-9f9f-e0e2949e2378.png)

**Comment by mgm8** [comment]
@YanAzer this is not a big issue, as can be seen [here](https://youtu.be/ECmqEms8u_Q?t=302), sometimes the RBF is removed before installing the satellite in the P-POD.

**Comment by YanAzer** [comment]
@mgm8 i already did the changes along the week, didn't commited because i didn't want to mix with the history of the N3 board on the recently pull request. Doing this change actually helped since i needed to move the picoblade headers (#27) and somewhat distributed the weight on both PCBs.
