### ISSUE TITLE
Hardware: Make a variant of Nº4 IIP board considering a camera opening

### ISSUE THREAD

**Issue by YanAzer** [spacelab-ufsc/interface-board#62]

**Comment by mgm8** [comment]
@YanAzer as the camera module is a just an idea for now, I think we can keep two variants of the Nº4 IIP board:

* One without any connector or components (a "blank" PCB)
* One with a camera "slot"

**Comment by YanAzer** [comment]
Noted @mgm8 just fixing the issue name for now.
